# See: https://etcd.io/docs/v3.5/op-guide/configuration/
# Follow: https://etcd.io/docs/v3.5/quickstart/

version: '3.1'

services:
  etcd0:
    image: quay.io/coreos/etcd:v3.5.0
    command: /usr/local/bin/etcd --name 'etcd0'
      --listen-client-urls 'http://0.0.0.0:2379,http://0.0.0.0:4001'
      --initial-advertise-peer-urls=http://192.168.12.50:2380
      --advertise-client-urls 'http://192.168.12.50:2379,http://192.168.12.50:4001'
      --listen-peer-urls 'http://0.0.0.0:2380'
      --initial-cluster-token etcd-cluster-1
      --initial-cluster 'etcd0=http://192.168.12.50:2380'
      --initial-cluster-state new
      --auto-compaction-retention=1
    volumes:
      - /usr/share/ca-certificates/:/etc/ssl/certs
    ports:
      - 2379:2379
      - 2380:2380
      - 4001:4001

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel/config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
